### ISSUE TITLE
reasonid=10 ?

### ISSUE THREAD

**Issue by Bluscream** [maddinat0r/samp-tsconnector#19]
https://github.com/maddinat0r/samp-tsconnector/blob/fbc4fc5c470a9ed6f9aca5d55dc0b0fb9d233545/src/CServer.cpp#L22

What reason is reasonid 10?

**Comment by maddinat0r** [comment]
`10` stands for "server or channel edited". As it's a event for a channel edit, `reasonid` is always `10`.

**Comment by Bluscream** [comment]
Ahh thanks :) I would suggest parsing the events instead of RegEx'ing them tho. Maybe Teamspeak or 3rd party servers like TeaSpeak change the order of the key/value pairs.

**Comment by maddinat0r** [comment]
Yeah I know, using regular expressions here isn't really the best solution. I'll replace it with a proper token parser eventually.

**Comment by Bluscream** [comment]
Thanks :>
