### ISSUE TITLE
CLIENT_DESCRIPTION

### ISSUE THREAD

**Issue by axi92** [maddinat0r/samp-tsconnector#9]
Please keep that in mind to change CLIENT_DESCRIPTION at some version in the future

**Comment by maddinat0r** [comment]
What exactly do you mean?

**Comment by axi92** [comment]
That the samp-tsconnector cant change the Description of a Client.
We use that to identify the exact name. Because the client cant change the "Client description" only we admins can do that so the client can change his name to what he want and we still know who that is.

**Comment by axi92** [comment]
Dont know if it helps but here is the PHP docu I am using this funktion:
https://docs.planetteamspeak.com/ts3/php/framework/_client_8php_source.html#l00062
